**Email address : ad.rahman142@gmail.com**

In [180]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


# **1) NumPy — 5 Questions**

## Ans to the Q1

In [181]:
ages = np.array(ages)
salaries = np.array(salaries)

print(ages)
print(salaries)

[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]


In [182]:
print(ages.dtype)
print(salaries.dtype)

print(ages.ndim)
print(salaries.ndim)

print(ages.shape)
print(salaries.shape)

print(ages.size)
print(salaries.size)

int64
int64
1
1
(10,)
(10,)
10
10


## Ans to the Q2

In [183]:
highest_salary = np.max(salaries)
lowest_salary = np.min(salaries)

print(f"Highest salary : {highest_salary}")
print(f"Lowest salary : {lowest_salary}")

Highest salary : 89735
Lowest salary : 30769


In [184]:
average_salary = np.mean(salaries)
average_age = np.mean(ages)

print(f"Average salary : {average_salary}")
print(f"Average age : {average_age}")

Average salary : 57446.9
Average age : 38.5


## Ans to the Q3

In [185]:
above_30 = ages[ages > 30]

print(above_30)
print(f"{above_30.size} employees are older than 30")

[56 46 32 38 56 36 40]
7 employees are older than 30


## Ans to the Q4

In [186]:
updated_ages = ages+5

print(updated_ages)

[61 51 37 30 43 61 41 45 33 33]


## Ans to the Q5

In [187]:
total_salary_expense = np.sum(salaries)

print(total_salary_expense)

574469


In [188]:
diff = np.max(salaries) - np.min(salaries)
print(diff)

58966


# **2) Pandas — 5 Questions**

## Ans to the Q6

In [189]:
df = pd.read_csv('employees.csv')

df.head(5)

,id,age,salary,dept
0,1,56,77191,HR
1,2,46,74131,IT
2,3,32,46023,Finance
3,4,25,71090,IT
4,5,38,31685,HR


In [190]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes


In [191]:
df.describe()

,id,age,salary
count,10.00000,10.00000,10.000000
mean,5.50000,38.50000,57446.900000
std,3.02765,11.16791,24357.262884
min,1.00000,25.00000,30769.000000
25%,3.25000,29.00000,33152.500000
50%,5.50000,37.00000,58556.500000
75%,7.75000,44.50000,76426.000000
max,10.00000,56.00000,89735.000000


## Ans to the Q7

In [192]:
df[['id', 'age', 'salary']]

,id,age,salary
0,1,56,77191
1,2,46,74131
2,3,32,46023
3,4,25,71090
4,5,38,31685
5,6,56,30769
6,7,36,89735
7,8,40,86101
8,9,28,32433
9,10,28,35311


In [193]:
df.tail(3)

,id,age,salary,dept
7,8,40,86101,IT
8,9,28,32433,Sales
9,10,28,35311,HR


## Ans to the Q8

In [194]:
it_dep = df.loc[df['dept']=='IT']
print(it_dep)
print("Total IT employees:", len(it_dep))

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
Total IT employees: 3


## Ans to the Q9

In [195]:
sorted_salary = df.sort_values('salary', ascending=False)
sorted_salary[['salary','dept', 'age']].head(3)

,salary,dept,age
6,89735,Finance,36
7,86101,IT,40
0,77191,HR,56


## Ans to the Q10

In [196]:
df.loc[df['salary'] > 80000, 'salary'] = 80000

new_average = df['salary'].mean()
print(new_average)

55863.3
