In [8]:
import numpy as np

arr1 = np.array([1,2,3,4,5])

In [10]:
# veiw the array not copy
v_arr = arr1[1:4]

v_arr[1] = 30

print(arr1)
print(v_arr)

[ 1  2 30  4  5]
[ 2 30  4]


In [11]:
# copy
arr1 = np.array([1,2,3,4,5])
cpy_arr = arr1[1:4].copy()

cpy_arr[1] = 30

print(arr1)
print(cpy_arr)

[1 2 3 4 5]
[ 2 30  4]


## Advance Indexing

In [14]:
lst = np.array([10,20,30,40,50])

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [19]:
lst = np.array([[10,20,30],[40,50,60]])

# name_of_list[[row], [column]]

values = lst[[0,1], [1,2]]

print(values)

[20 60]


In [21]:
# boolean way
print(lst[lst>20])

[30 40 50 60]


In [23]:
lst[lst <= 20] = 0

print(lst)

[[ 0  0 30]
 [40 50 60]]


## Iteration

In [25]:
arr = np.array([[10,20,30],[40,50,60]])

for i in np.nditer(arr):
    print(i)

10
20
30
40
50
60
