In [7]:
import numpy as np

lst = [10, 20, 30, 40, 50.5]    # with a float value

arr = np.array(lst, dtype = np.int32)

print(arr.dtype)
print(type(arr))
print(arr)

int32
<class 'numpy.ndarray'>
[10 20 30 40 50]


In [14]:
mixed_lst = [10, True, 'hello', 10.5]

arr2 = np.array(mixed_lst)

print(arr2)
print(arr2.dtype)

['10' 'True' 'hello' '10.5']
<U32


In [15]:
#tuple 

tpl = (10,20,30) 

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype) 
arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [16]:
#set 

st = { 1, 2, 3 }        # set can't be directly converted into Ndarray

arr = np.array(list(st))
# print(arr.dtype) 
arr = arr.astype(np.int16)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [17]:
# dictionary 

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [18]:
#items to ndarray
arr = np.array(list(items))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6
