In [21]:
import numpy as np

# np.zeros

arr = np.zeros((2,3))

print(arr)
print(arr.dtype)
arr = arr.astype(np.int8)
print(type(arr))
print(arr)
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
<class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]]
int8
(2, 3)
2
6


In [11]:
arr0 = [[[1,2,3], [3,4,5]], [[1,2,3], [3,4,5]], [[1,2,3], [3,4,5]]]

arr3 = np.array(arr3)

print(arr3)
print(arr.ndim)

[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]]
3


In [13]:
arr = np.zeros_like(arr3)

print(arr)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [43]:
# np.ones

arr = np.ones((4,3))

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12


In [25]:
arr = np.ones((3,2,3), dtype = np.int64)

print(arr)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [44]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim)
# print(arr.size)

arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

[[[9218868437227405312 9218868437227405312 9218868437227405312]
  [9218868437227405312 9218868437227405312 9218868437227405312]]

 [[9218868437227405312 9218868437227405312 9218868437227405312]
  [9218868437227405312 9218868437227405312 9218868437227405312]]

 [[9218868437227405312 9218868437227405312 9218868437227405312]
  [9218868437227405312 9218868437227405312 9218868437227405312]]]
(3, 2, 3)


In [38]:
#np.full 

arr = np.full((4,3),np.inf)

# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim)
# print(arr.size)


arr = np.full_like(arr3,np.inf,dtype=np.float64) 

print(arr)
print(arr.shape)
print(arr.dtype)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64
