In [5]:
import numpy as np

arr = np.random.rand(2,3) # 0 to 1 range

print(arr)

[[0.10423714 0.35781514 0.28939384]
 [0.2763222  0.97170325 0.65843568]]


In [12]:
# np.random.randint(start,end, shape)

arr = np.random.randint(0,10, (3,5))

print(arr)
print(arr.dtype)

[[3 9 2 2 5]
 [1 1 7 0 0]
 [4 1 5 8 8]]
int32


In [14]:
# np.random.uniform(start,end, shape) 

arr = np.random.uniform(50,100, (3,3,4))   

print(arr) 

[[[54.57790701 66.24720466 83.34275878 52.96052766]
  [77.79988476 82.22927831 75.6025607  70.75884273]
  [89.10115526 70.79432218 59.82631639 69.2963015 ]]

 [[85.5875711  56.47142465 75.12364622 81.8007644 ]
  [76.02405602 95.59319639 99.78078507 83.34124999]
  [64.26712551 56.59373267 76.12684172 51.73633298]]

 [[55.28633217 88.4337452  65.28945839 81.45927221]
  [92.27063707 68.32641352 66.15154383 56.28204851]
  [92.89445099 91.27668831 71.44380617 56.36095698]]]
