In [7]:
import numpy as np

arr1 = np.array([1,2,3,4,5])

arr2 = np.array([[1,2,3], [4,5,6]])

2

In [10]:
#indexing 
arr1[2] = 10

print(arr1)

arr2[0][2]= 10

print(arr2)

[ 1  2 10  4  5]
[[ 1  2 10]
 [ 4  5  6]]


In [12]:
#slicing 
#1d = arr[start:end:step] 

arr1_mod = arr1[1:4]    # as view

print(arr1_mod)

[ 2 10  4]


In [13]:
#2d slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2) 

#getting a row 

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column 

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion 

portion = arr2[:: , 0:2] 

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]
