In [2]:
import numpy as np

In [98]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b.shape)

(2, 3)


In [3]:
arr = np.random.randint(1,100, size = (10,5))

print(arr)

[[ 5 15 74 64 55]
 [11  1 73 89 12]
 [56 97 68 64  2]
 [62  3 68 93 25]
 [55 42 60 13 57]
 [37 48 71 65 61]
 [15  8 29 13 58]
 [16 36 76 25 68]
 [49 39 87 26 56]
 [17 85  7 52 70]]


In [4]:
print(arr.shape)

(10, 5)


In [5]:
b = arr.reshape(5,10)
print(b.shape)
print(b)

(5, 10)
[[ 5 15 74 64 55 11  1 73 89 12]
 [56 97 68 64  2 62  3 68 93 25]
 [55 42 60 13 57 37 48 71 65 61]
 [15  8 29 13 58 16 36 76 25 68]
 [49 39 87 26 56 17 85  7 52 70]]


In [6]:
flatten = b.flatten()
print(flatten.ndim)
print(flatten)

1
[ 5 15 74 64 55 11  1 73 89 12 56 97 68 64  2 62  3 68 93 25 55 42 60 13
 57 37 48 71 65 61 15  8 29 13 58 16 36 76 25 68 49 39 87 26 56 17 85  7
 52 70]


In [7]:
column_flattening = np.ravel(b, order = 'F')
print(column_flattening)

row_flattening = np.ravel(b, order = 'C')
print(row_flattening)

[ 5 56 55 15 49 15 97 42  8 39 74 68 60 29 87 64 64 13 13 26 55  2 57 58
 56 11 62 37 16 17  1  3 48 36 85 73 68 71 76  7 89 93 65 25 52 12 25 61
 68 70]
[ 5 15 74 64 55 11  1 73 89 12 56 97 68 64  2 62  3 68 93 25 55 42 60 13
 57 37 48 71 65 61 15  8 29 13 58 16 36 76 25 68 49 39 87 26 56 17 85  7
 52 70]


## Concatenate

In [8]:
a = np.random.randint(1,10, size = (2,3))
b = np.random.randint(11,20, size = (2,3))
print(a)
print(b)

[[7 7 2]
 [6 2 5]]
[[18 19 17]
 [16 17 15]]


In [9]:
con = np.concatenate((a,b), axis = 0)    # row wise (must be the both array column same)
print(con)

con = np.concatenate((a,b), axis = 1)    # column wise (must be the both array row same)
print(con)

[[ 7  7  2]
 [ 6  2  5]
 [18 19 17]
 [16 17 15]]
[[ 7  7  2 18 19 17]
 [ 6  2  5 16 17 15]]


In [10]:
# error

# row wise concetanate korar shomoi column same thakbe 
# col wise concat korar shomoi row ta same thakte hobe 

x = np.random.randint(1,10, size = (2,3))
y = np.random.randint(11,20, size = (1,3))
print(x)
print(y)

[[5 6 1]
 [3 5 3]]
[[17 16 19]]


In [11]:
con = np.concatenate((x,y), axis = 0)    # column size same
print(con)

# throw an error
con = np.concatenate((x,y), axis = 1)    # row size are not same
print(con)

[[ 5  6  1]
 [ 3  5  3]
 [17 16 19]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

## Transpose

In [ ]:
mat = np.array([[1,2,3],
                [4,5,6]])

transpose = mat.T

print(transpose)

## Array Split

In [ ]:
x = np.random.randint(1,10, size = (10))
print(x)

splitted_array = np.array_split(x,3)

print(splitted_array)


# split -> for equal division 
splitted_array = np.split(x,2)
print(splitted_array)

# throw an error
splitted_array = np.split(x,3)
print(splitted_array)

## arithmatic operator

In [16]:
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = x+y
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainders = x%y
print(remainders)

s = np.sum(x)
print(s)

cumulative_sum = np.cumulative_sum(x)    # prefix sum
print(cumulative_sum)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]
100
[ 10  30  60 100]


## mathematical function

In [ ]:
# trigonometry

# sin , cos , tan takes values in radian 
sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

tan_val = np.tan(x)
print(tan_val)

deg_con = np.rad2deg(x)
print(deg_con)

ran_con = np.deg2rad(x)
print(x)


In [14]:
# log
x = np.array([ 10 , 8 , 16 , 100 ])

base_10_log = np.log10(x)
print(base_10_log)

two_diye_bhag = np.log2(x) 
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


## broadcasting

In [21]:
x = np.array([ 10 , 8 , 16 , 100 ])

result = x**2

print(result)

matrix = np.array([[1,2,3],[4,5,6]])

vector = np.array([1,2,3])

result = matrix + vector    #rulings = columns er size and vector er size same hote hobe 

print(result)

[  100    64   256 10000]
[[2 4 6]
 [5 7 9]]


## Logical Function

In [22]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ]) 

greater_than = x>y 

print(greater_than)

equal = x==y 

print(equal) 

# all () -> shob true kina 
# any() -> jekono ekta true ase kina 

print(np.all(greater_than))    # if all value have true, then it's returns true (like 'and')

print(np.any(equal))    # if any value have true, then it's returns true (like 'or')

[ True  True False  True]
[False False  True False]
False
True


## Sorting

In [39]:
#inplace 
x = np.array([ 10 , 8 , 16 , 100])

x.sort()

print(x)    # not have the old 'x'

[  8  10  16 100]


In [42]:
# copy sorting
x = np.array([ 10 , 8 , 16 , 100])
print(x)

sort_arr = np.sort(x) 

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [40]:
# 2d array sorting 
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1 

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching

In [44]:
# np.where( condition , x , y ) if true x , otherwise replace with y 
print(x)

index = np.where(x==8) # returns x index
print(index)

arr = np.where(x>8,x,0) # returns array 
print(arr)

[ 10   8  16 100]
(array([1]),)
[ 10   0  16 100]


In [47]:
print(mat)
index = np.where(mat==8) # returns x, y index
print(index)

arr = np.where(mat>8,mat,0) # returns array 
print(arr)

[[10  3  5]
 [ 8  4  9]]
(array([1]), array([0]))
[[10  0  0]
 [ 0  0  9]]


In [54]:
x = np.array([ 10, 100 , 8 , 16 , 100 ])
print(x)

max_value = np.max(x)
maximum_value_indx = np.argmax(x) 
print(f"Max value: {max_value}, Max value Index: {maximum_value_indx}")

min_value = np.min(x)
minimum_value_indx = np.argmin(x)
print(f"Min value: {min_value}, Minimum value Index: {minimum_value_indx}")


[ 10 100   8  16 100]
Max value: 100, Max value Index: 1
Min value: 8, Minimum value Index: 2


## Counting

In [55]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[63 99 47 42 93 51 39 77 92 16 36 89 22 32 81  8 35 76 84 35 48 35 77 56
 55  2  8 21 32  5 40 65 16 81 25  9 62 36 64 59 28 67 45 99 16 51 98 52
 47 32 50 51 36  9 25 96 65 73 58 37 98 23 80 93 57 54 27  5 31 86 46 67
 57 31 75 13 53 66 70  2  9 41 78 58 38 21 68 18 39 22  7  9 55 93 26 66
 22 29 24 80]


In [57]:
count = np.count_nonzero(a<30)    # can be use any conditions
print(count)

29


In [59]:
# unique value
unique_value = np.unique(a)

print(unique_value)

[ 2  5  7  8  9 13 16 18 21 22 23 24 25 26 27 28 29 31 32 35 36 37 38 39
 40 41 42 45 46 47 48 50 51 52 53 54 55 56 57 58 59 62 63 64 65 66 67 68
 70 73 75 76 77 78 80 81 84 86 89 92 93 96 98 99]


In [62]:
unique_value,count = np.unique(a, return_counts = True)

print(unique_value)
print(count)

[ 2  5  7  8  9 13 16 18 21 22 23 24 25 26 27 28 29 31 32 35 36 37 38 39
 40 41 42 45 46 47 48 50 51 52 53 54 55 56 57 58 59 62 63 64 65 66 67 68
 70 73 75 76 77 78 80 81 84 86 89 92 93 96 98 99]
[2 2 1 2 4 1 3 1 2 3 1 1 2 1 1 1 1 2 3 3 3 1 1 2 1 1 1 1 1 2 1 1 3 1 1 1 2
 1 2 2 1 1 1 1 2 2 2 1 1 1 1 1 2 1 2 2 1 1 1 1 3 1 2 2]


## Statistical Functions

In [70]:
# data load

data = np.genfromtxt('student_scores.csv', delimiter = ',', skip_header = 1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [80]:
# statistics  

eng_marks = data[::, :1]

print(eng_marks.T)

max_eng_mark = np.max(eng_marks)
print(max_eng_mark)

min_eng_mark = np.min(eng_marks)
print(min_eng_mark)

average_eng_mark = np.mean(eng_marks)
print(average_eng_mark)

median_eng_mark = np.median(eng_marks)
print(median_eng_mark) 

# standard deviation

std_eng_mark = np.std(eng_marks)
print(std_eng_mark)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [86]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

print(data.ndim)

# correlation coefficient

correlation = np.corrcoef(data)

print(correlation)

[[ 2  4  5  7  8]
 [65 75 78 88 92]]
[[1.         0.99859154]
 [0.99859154 1.        ]]


## linear algebra

In [88]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe 
dot_product = np.dot(A,B)
print(dot_product)

# trace 
print(np.trace(B))

[[ 58  64]
 [139 154]]
17


In [93]:
sq_mat = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# determinant 
det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

-9.51619735392994e-16
2


In [100]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]
