In [1]:
import numpy as np

## problem_1

In [4]:
arr1 = np.array([1,2,3])

arr2 = np.array([[1,2,3],[4,5,6]])

arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

print(arr3.ndim)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)

1
(3,)
3
int64
2
(2, 3)
6
int64
3
(3, 2, 3)
18
int64


## problem_2

In [15]:
z = np.zeros((3,3))
print(z)
print(z.shape)

o = np.ones((2,5))
print(o)
print(o.shape)

# 1D
f = np.full((5,),7)
print(f)
print(f.shape)

# 2D
f = np.full((3,4),7)
print(f)
print(f.shape)

# 3D
f = np.full((3,3,4),7)
print(f)
print(f.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)
[7 7 7 7 7]
(5,)
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
(3, 4)
[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]
(3, 3, 4)


## problem_3

In [21]:
arr = np.arange(10,50,2)
print(arr)

arr = np.linspace(10,50,20)
print(arr)

arr = np.logspace(10,50,20)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[10.         12.10526316 14.21052632 16.31578947 18.42105263 20.52631579
 22.63157895 24.73684211 26.84210526 28.94736842 31.05263158 33.15789474
 35.26315789 37.36842105 39.47368421 41.57894737 43.68421053 45.78947368
 47.89473684 50.        ]
[1.00000000e+10 1.27427499e+12 1.62377674e+14 2.06913808e+16
 2.63665090e+18 3.35981829e+20 4.28133240e+22 5.45559478e+24
 6.95192796e+26 8.85866790e+28 1.12883789e+31 1.43844989e+33
 1.83298071e+35 2.33572147e+37 2.97635144e+39 3.79269019e+41
 4.83293024e+43 6.15848211e+45 7.84759970e+47 1.00000000e+50]


## problem_4

In [25]:
arr = np.random.randint(10, size=(4,4))
print(arr)

[[9 2 5 9]
 [7 8 3 1]
 [1 2 8 6]
 [7 6 4 9]]


In [38]:
first_row = arr[:1,].copy()
# print(first_row)

last_col = arr[::, 3:].copy()
print(last_col)

center = arr[1:3, 1:3].copy()
print(center)

[[9]
 [1]
 [6]
 [9]]
[[8 3]
 [2 8]]


## problem_5

In [60]:
a = np.array([1,2,3])

b = np.random.randint(10, size = (3,3))
print(b)

[[1 3 3]
 [8 2 9]
 [1 5 4]]


In [61]:
add = np.add(a,b)
print(add)

[[ 2  5  6]
 [ 9  4 12]
 [ 2  7  7]]


## problem_6

In [73]:
A = np.linspace(1,100,20)
B = np.arange(0,20)
C = np.random.randint(10,100,20)
print(C)
print((A+B)/2)
print((A**2)+(B**2))

[38 50 79 88 48 62 12 68 38 24 90 99 95 10 41 53 94 96 21 54]
[ 0.5         3.60526316  6.71052632  9.81578947 12.92105263 16.02631579
 19.13157895 22.23684211 25.34210526 28.44736842 31.55263158 34.65789474
 37.76315789 40.86842105 43.97368421 47.07894737 50.18421053 53.28947368
 56.39473684 59.5       ]
[1.00000000e+00 3.95706371e+01 1.34440443e+02 2.85609418e+02
 4.93077562e+02 7.56844875e+02 1.07691136e+03 1.45327701e+03
 1.88594183e+03 2.37490582e+03 2.92016898e+03 3.52173130e+03
 4.17959280e+03 4.89375346e+03 5.66421330e+03 6.49097230e+03
 7.37403047e+03 8.31338781e+03 9.30904432e+03 1.03610000e+04]
